# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: db0faa71da5cae2d6d132831e6f561f8188043c9f91a272d08df1b75cd38143e45d6746eef9f39aa5352078c0229c02f7ce859ec7b0057a92681b8803bf61f52

test:
  secret_key_base: d95d4d4b2c55b189c3822f073a973395bb72605b3cd2ae06030c2e5a7b2f861958938a8122ccfdf81465792f26544101043d30d4c8ae037d2472876180c1b9ac

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
